@ServiceMesh.Demo_HostAddress = https://localhost:55156

@a=0
@b=0
GET {{ServiceMesh.Demo_HostAddress}}/api/demo/calculate?a={{a}}&b={{b}}

###

@serviceName="LisView"
GET {{ServiceMesh.Demo_HostAddress}}/api/demo/discover/{{serviceName}}

###

GET {{ServiceMesh.Demo_HostAddress}}/api/demo/error

###

GET {{ServiceMesh.Demo_HostAddress}}/api/demo/info

###

GET {{ServiceMesh.Demo_HostAddress}}/api/demo/slow

###

GET {{ServiceMesh.Demo_HostAddress}}/api/demo/info

###

GET {{ServiceMesh.Demo_HostAddress}}/api/demo/services

###

GET {{ServiceMesh.Demo_HostAddress}}/api/demo/instances

###
